language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
env:
  global:
    - COVERALLS_REPO_TOKEN=L6wwcwROnM74htYHs0siaF2t3QidGSvyv
cache:
  directories:
  - node_modules
  - .bower-registry
  - .bower-cache
  - app/bower_components
